
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    TEAM_ID INTEGER,
    STUDENT_ID INTEGER,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    ROLE VARCHAR(255)
);

CREATE TABLE STUDENTS(
    STUDENT_ID INTEGER PRIMARY KEY,
    STUDENT_PROGRAM VARCHAR(255),
    COURSE_SECTION VARCHAR(255)
);

CREATE TABLE TEAMS(
    ID SERIAL PRIMARY KEY
)

